image: loicmdivad/edml-cicd-base:0.1.1-SNAPSHOT

variables:
  PIP_CACHE_DIR: out/.pip
  MAVEN_REPO: out/.m2
  MAVEN_OPTS: "-Dmaven.repo.local=${MAVEN_REPO}/repository"
  MAVEN_CONFIG: "-s ${MAVEN_REPO}/settings.xml"

before_script:
  - mkdir -p ${MAVEN_REPO}
  - envsubst < settings.template.xml > ${MAVEN_REPO}/settings.xml

stages:
  - test
  - package
  - deploy-app/train
  - deploy-model

cache:
  key: EDML_CACHING_KEY
  paths:
    - ${MAVEN_REPO}/
    - ${PIP_CACHE_DIR}/
  policy: pull-push

.manual_submission: &manual_submission
  except:
    variables:
      - $TRAIN_VERSION

.manual_publication: &manual_publication
  except:
    variables:
      - $DEPLOY_PATH
      - $DEPLOY_VERSION
test:
  stage: test
  <<: *manual_submission
  <<: *manual_publication
  script:
    - ./mvnw -B test

package:
  stage: package
  <<: *manual_submission
  <<: *manual_publication
  script:
    - ./mvnw -B package jib:build -DskipTests
    - gsutil cp ./edml-serving/target/edml-serving*.jar gs://edml/maven/edml-serving/
    - gsutil cp ./edml-scoring/target/edml-scoring*.jar gs://edml/maven/edml-scoring/
    - gsutil cp ./edml-trainer/target/dist/edml_trainer*.whl gs://edml/pypi/edml-trainer/

.training: &training
  script:
    - export PROJECT_VERSION=$(eval $PROJECT_VERSION_CMD)
    - export PY_PROJECT_VERSION=$(eval $PY_PROJECT_VERSION_CMD)
    - echo "Prepare Job submition with artifact ${PY_PROJECT_VERSION}"
    - mkdir -p ./out && cd ./out
    - gsutil -m cp gs://edml/pypi/edml-trainer/edml_trainer*${PY_PROJECT_VERSION}*.whl .
    - unzip edml_trainer*
    - gcloud ai-platform jobs list
    - ./ai-platform-submit.sh ${PROJECT_VERSION}

train:
  stage: deploy-app/train
  <<: *manual_submission
  <<: *manual_publication
  variables:
    PROJECT_VERSION_CMD: 'maven-eval \$${edml.revision}'
    PY_PROJECT_VERSION_CMD: 'echo $$PROJECT_VERSION | tr "-" "_"'
  <<: *training

on-demand-model-training:
  stage: deploy-app/train
  <<: *manual_publication
  only:
    variables:
      - $TRAIN_VERSION
  variables:
    PROJECT_VERSION_CMD: 'echo $$TRAIN_VERSION'
    PY_PROJECT_VERSION_CMD: 'echo $$PROJECT_VERSION | tr "-" "_"'
  <<: *training

deploy-model:
  stage: deploy-model
  <<: *manual_publication
  when: manual
  only:
    - trunk
  script:
    - MODEL_VERSION=${MODEL_ID} MODEL_PATH=${MODEL_PATH}/ /app/bin/edml-cicd-base
  dependencies:
    - train
    - on-demand-model-training
  allow_failure: false

on-demand-model-deployement:
  stage: deploy-model
  when: manual
  only:
    - trunk
  script:
    - MODEL_VERSION=${DEPLOY_VERSION} MODEL_PATH=${DEPLOY_PATH}/ /app/bin/edml-cicd-base
  allow_failure: false

deploy-app:
  stage: deploy-app/train
  <<: *manual_submission
  <<: *manual_publication
  when: manual
  only:
    - trunk
  script:
    - echo "I'm deploying now"
