image: loicmdivad/edml-cicd-base:0.1.1-SNAPSHOT

variables:
  PIP_CACHE_DIR: out/.pip
  MAVEN_REPO: out/.m2
  MAVEN_OPTS: "-Dmaven.repo.local=${MAVEN_REPO}/repository"
  MAVEN_CONFIG: "-s ${MAVEN_REPO}/settings.xml"

before_script:
  - mkdir -p ${MAVEN_REPO}
  - envsubst < settings.template.xml > ${MAVEN_REPO}/settings.xml

stages:
  - test
  - package
  - deploy-app/train
  - deploy-model

cache:
  key: EDML_CACHING_KEY
  paths:
    - ${MAVEN_REPO}/
    - ${PIP_DOWNLOAD_CACHE}/
  policy: pull-push

.manual_submission: &manual_submission
  except:
    variables:
      - $TRAIN_VERSION

test:
  stage: test
  <<: *manual_submission
  script:
    - ./mvnw -B test

package:
  stage: package
  <<: *manual_submission
  script:
    - ./mvnw -B package jib:build -DskipTests
    - gsutil cp ./edml-serving/target/edml-serving*.jar gs://edml/maven/edml-serving/
    - gsutil cp ./edml-scoring/target/edml-scoring*.jar gs://edml/maven/edml-scoring/
    - gsutil cp ./edml-trainer/target/dist/edml_trainer*.whl gs://edml/pypi/edml-trainer/

.training: &training
  script:
    - export PROJECT_VERSION=$(PROJECT_VERSION_CMD)
    - export PY_PROJECT_VERSION=$(PY_PROJECT_VERSION_CMD)
    - echo "Prepare Job submition with artifact ${PY_PROJECT_VERSION}"
    - mkdir -p ./out && cd ./out
    - gsutil -m cp gs://edml/pypi/edml-trainer/edml_trainer*${PY_PROJECT_VERSION}*.whl .
    - unzip edml_trainer*
    - gcloud ai-platform jobs list
    - scripts/ai-platform-submit.sh ${PROJECT_VERSION}

train:
  stage: deploy-app/train
  <<: *manual_submission
  variables:
    PROJECT_VERSION_CMD: 'maven-eval "\${edml.revision}"'
    PY_PROJECT_VERSION_CMD: 'tr "-" "_" <<(echo $PROJECT_VERSION)'
  <<: *training

on-demand-train:
  stage: deploy-app/train
  only:
    variables:
      - $TRAIN_VERSION
  variables:
    PROJECT_VERSION_CMD: 'eval $TRAIN_VERSION'
    PY_PROJECT_VERSION_CMD: 'tr "-" "_" <<(echo $PROJECT_VERSION)'
  <<: *training

deploy-model:
  when: manual
  only:
    - trunk
  stage: deploy-model
  script:
    - export BUCKET=$(cat ./build/version.properties | grep -i model_path | awk -F= '{print $2}')
    - export VERSION=$(cat ./build/version.properties | grep -i model_version | awk -F= '{print $2}')
    - export EXPORT=$(gsutil ls ${BUCKET}/model/export/exporter/ | sort | tail -1)
    - MODEL_VERSION=${VERSION} MODEL_PATH=${EXPORT}/ /app/bin/edml-cicd-base
  dependencies:
    - train
    - on-demand-train
  allow_failure: false

deploy-app:
  stage: deploy-app/train
  <<: *manual_submission
  when: manual
  only:
    - trunk
  script:
    - echo "I'm deploying now"
