concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner"
  url = "http://gitlab.europe-west2-b.c.event-driven-ml.internal:80/"
  token = "Nv1-MLwzrzSjvEzhdsgV"
  executor = "docker"
  clone_url = "http://gitlab.europe-west2-b.c.event-driven-ml.internal:80/"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "gcr.io/event-driven-ml/edml-cicd:0.1.0"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "docker-runner"
  url = "http://gitlab.europe-west2-b.c.event-driven-ml.internal:80/"
  token = "uyyLxY8dtUAw6B6jN3kW"
  executor = "docker"
  clone_url = "http://gitlab.europe-west2-b.c.event-driven-ml.internal:80/"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "gcr.io/event-driven-ml/edml-cicd:0.1.0"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "docker-runner"
  url = "http://gitlab.europe-west2-b.c.event-driven-ml.internal:80/"
  token = "zxz6LsosHh9gnsFfSFQN"
  executor = "docker"
  clone_url = "http://gitlab.europe-west2-b.c.event-driven-ml.internal:80/"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "gcr.io/event-driven-ml/edml-cicd:0.1.0"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]