apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: direct
    orgId: 1
    url: https://www.f7f72e0.xebilolo.com
    isDefault: true

    version: 1
    editable: false

