{
 "title": "EDML Project (PS Engineering)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pick and Dropff replay (2019-11-28)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_send_rate{job=\"replay-pickup\"} * 60",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "kafka_producer_producer_metrics_record_send_rate{job=\"replay-dropoff\"} * 60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "System CPU Load",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RMSE - edml, taxi trip prediction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_edml_taxi_trip_duration_rmse",
     "legendFormat": "{{job}} {{model_version}}"
    }
   ]
  },
  {
   "title": "Records Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, topic)(kafka_consumer_consumer_fetch_manager_metrics_records_lag)",
     "legendFormat": "{{job}}: {{topic}}"
    }
   ]
  },
  {
   "title": "Prediction / Result Join",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic)((kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{job=\"edml-scoring\", topic=~\"EDML-PREDICTION-TOPIC|TAXI-TRIP-DROPOFF-REPLAY\"})) * 60",
     "legendFormat": "{{job}}: {{topic}}"
    },
    {
     "expr": "kafka_producer_producer_topic_metrics_record_send_rate{topic=\"EDML-TRIP-SCORING-KSTREAM-JOINOTHER-0000000005-store-changelog\"} * 60",
     "legendFormat": "Joined"
    }
   ]
  },
  { "title": "Model Notifications", "type": "alertlist", "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 } },
  {
   "title": "Model Trigger",
   "type": "graph",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_max(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{topic=\"EDML-MODEL-TOPIC\"} * 60, 1)",
     "legendFormat": "EDML1"
    }
   ]
  }
 ]
}