apiVersion: apps/v1
kind: Deployment
metadata:
  name: replay-pickup-app
  namespace: default
  labels:
    app: replay-pickup-app
spec:
  selector:
    matchLabels:
      app: replay-pickup-app
  template:
    metadata:
      labels:
        app: replay-pickup-app
    spec:
      containers:
        - name: replay-pickup
          image: gcr.io/event-driven-ml/edml-replay:latest
          env:
            - name: SOURCE_TOPIC
              value: TAXI-TRIP-PICKUP-2018-11-28
            - name: REPLAY_TOPIC
              value: TAXI-TRIP-PICKUP-REPLAY
            - name: DATE_TIME_COLUMN
              value: pickup_datetime
            - name: CONSUMER_GROUP
              value: edml-pickup-replay-2018-11-28
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: api-key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: secret-key
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: bootstrap-servers
            - name: SR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: sr-api-key
            - name: SR_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: sr-secret-key
            - name: SCHEMA_REGISTRY_URL
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: schema-registry-url
            - name: SASL_CLASS
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: sasl-class
            - name: ROOT_LOG_LVL
              value: INFO
---
apiVersion: v1
kind: Service
metadata:
  name: replay-pickup-service
  namespace: default
  labels:
    app: replay-pickup-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
  selector:
    app: replay-pickup-app
