apiVersion: apps/v1
kind: Deployment
metadata:
  name: edml-serving-app
  namespace: default
  labels:
    app: edml-serving-app
spec:
  selector:
    matchLabels:
      app: edml-serving-app
  template:
    metadata:
      labels:
        app: edml-serving-app
    spec:
      containers:
        - name: edml-serving
          image: gcr.io/event-driven-ml/edml-serving:latest
          env:
            - name: PICKUP_TOPIC
              value: TAXI-TRIP-PICKUP-REPLAY
            - name: PREDIC_TOPIC
              value: EDML-PREDICTION-TOPIC
            - name: MODEL_PREFIX
              value: EDML-MODEL
            - name: APPLICATION_ID
              value: EDML-TRIP-DURATION
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: api-key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: secret-key
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: bootstrap-servers
            - name: SR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: sr-api-key
            - name: SR_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: sr-secret-key
            - name: SCHEMA_REGISTRY_URL
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: schema-registry-url
            - name: SASL_CLASS
              valueFrom:
                secretKeyRef:
                  name: confluent-secrets
                  key: sasl-class
            - name: ROOT_LOG_LVL
              value: INFO
---
apiVersion: v1
kind: Service
metadata:
  name: edml-serving-service
  namespace: default
  labels:
    app: edml-serving-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
  selector:
    app: edml-serving-app
